nameOverride: ""
fullnameOverride: "mongodb"

namespace:
  name: mongodb
  create: false

mongodb:
  image:
    repository: mongo
    tag: "7.0"
    pullPolicy: IfNotPresent

  replicaSet:
    name: rs0
    replicas: 3

  auth:
    rootUsername: admin
    rootPassword: "Admin@123"
    # Replace in prod
    replicaSetKey: "VGhpcyBpcyBhIGRlZmF1bHQga2V5LiBQbGVhc2UgY2hhbmdlIGluIHByb2R1Y3Rpb24h"

  storage:
    # Container path (keep as-is)
    dbPath: /data/db

    # Match your PV size
    size: 5Gi

    # Match your StorageClass
    storageClassName: local-storage

    cacheSizeGB: 1
    oplogSizeMB: 1024

  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "500m"
      cpu: "512Mi"

  service:
    type: ClusterIP
    port: 27017
    nodePort: null

  # Force pods to run on your node
  nodeSelector:
    kubernetes.io/hostname: stag-master-01

  podAntiAffinity: soft

securityContext:
  fsGroup: 999
  runAsUser: 999
