apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mongodb-ha.fullname" . }}-init-replicaset
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "mongodb-ha.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        {{- include "mongodb-ha.selectorLabels" . | nindent 8 }}
        job-name: {{ include "mongodb-ha.fullname" . }}-init-replicaset
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongo-init
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail

              RELEASE_FULLNAME="{{ include "mongodb-ha.fullname" . }}"
              NAMESPACE="{{ .Values.namespace.name }}"
              MONGO_PORT={{ .Values.mongodb.service.port }}
              RS_NAME="{{ .Values.mongodb.replicaSet.name }}"
              ROOT_USER="{{ .Values.mongodb.auth.rootUsername }}"
              ROOT_PWD="{{ .Values.mongodb.auth.rootPassword }}"
              REPLICAS={{ .Values.mongodb.replicaSet.replicas }}

              POD0_FQDN="${RELEASE_FULLNAME}-0.${RELEASE_FULLNAME}-service.${NAMESPACE}.svc.cluster.local:${MONGO_PORT}"

              echo "[init-job] Waiting for MongoDB pod-0 at ${POD0_FQDN}..."

              MAX_ATTEMPTS=60
              SLEEP=5
              ATTEMPT=0

              until mongosh --host "${POD0_FQDN}" --eval "db.adminCommand('ping')" >/dev/null 2>&1 || [ $ATTEMPT -ge $MAX_ATTEMPTS ]; do
                ATTEMPT=$((ATTEMPT+1))
                echo "[init-job] Attempt ${ATTEMPT}/${MAX_ATTEMPTS} - waiting ${SLEEP}s..."
                sleep ${SLEEP}
              done

              if [ $ATTEMPT -ge $MAX_ATTEMPTS ]; then
                echo "[init-job] ERROR: MongoDB pod-0 did not become reachable"
                exit 1
              fi

              echo "[init-job] ✓ MongoDB pod-0 is reachable"

              # Check if replica set is already initialized
              echo "[init-job] Checking replica set status..."
              RS_STATUS=$(mongosh --host "${POD0_FQDN}" --quiet --eval 'try { JSON.stringify(rs.status()) } catch(e) { "NOT_INITIALIZED" }' 2>/dev/null || echo "NOT_INITIALIZED")

              if echo "${RS_STATUS}" | grep -q '"ok".*1'; then
                echo "[init-job] ✓ Replica set already initialized"
              else
                echo "[init-job] Initializing replica set ${RS_NAME}..."
                
                MEMBERS=""
                for i in $(seq 0 $((REPLICAS-1))); do
                  if [ $i -eq 0 ]; then
                    PRIORITY=2
                  else
                    PRIORITY=1
                  fi
                  
                  if [ -n "$MEMBERS" ]; then
                    MEMBERS="${MEMBERS},"
                  fi
                  
                  MEMBERS="${MEMBERS}{ _id:${i}, host:'${RELEASE_FULLNAME}-${i}.${RELEASE_FULLNAME}-service.${NAMESPACE}.svc.cluster.local:${MONGO_PORT}', priority:${PRIORITY} }"
                done

                mongosh --host "${POD0_FQDN}" --eval "rs.initiate({_id: '${RS_NAME}', members:[${MEMBERS}]})"
                
                echo "[init-job] Waiting 30s for replica set to stabilize..."
                sleep 30
              fi

              # Wait for PRIMARY
              echo "[init-job] Waiting for PRIMARY to be elected..."
              ATTEMPT=0
              MAX_ATTEMPTS=30
              until mongosh --host "${POD0_FQDN}" --quiet --eval 'rs.status().members.find(m => m.stateStr === "PRIMARY")' | grep -q "PRIMARY" || [ $ATTEMPT -ge $MAX_ATTEMPTS ]; do
                ATTEMPT=$((ATTEMPT+1))
                echo "[init-job] Waiting for PRIMARY... (${ATTEMPT}/${MAX_ATTEMPTS})"
                sleep 2
              done

              if [ $ATTEMPT -ge $MAX_ATTEMPTS ]; then
                echo "[init-job] WARNING: PRIMARY not elected within timeout, but continuing..."
              else
                echo "[init-job] ✓ PRIMARY elected"
              fi

              # Create admin user
              echo "[init-job] Checking for admin user..."
              USER_CHECK=$(mongosh --host "${POD0_FQDN}" --quiet --eval "try { db.getSiblingDB('admin').getUser('${ROOT_USER}') } catch(e) { null }" 2>/dev/null || echo "null")

              if echo "${USER_CHECK}" | grep -q "null"; then
                echo "[init-job] Creating admin user '${ROOT_USER}'..."
                mongosh --host "${POD0_FQDN}" --eval "
                  admin = db.getSiblingDB('admin');
                  admin.createUser({
                    user: '${ROOT_USER}',
                    pwd: '${ROOT_PWD}',
                    roles: [
                      { role: 'root', db: 'admin' },
                      { role: 'clusterAdmin', db: 'admin' },
                      { role: 'userAdminAnyDatabase', db: 'admin' },
                      { role: 'dbAdminAnyDatabase', db: 'admin' },
                      { role: 'readWriteAnyDatabase', db: 'admin' }
                    ]
                  });
                "
                echo "[init-job] ✓ Admin user created"
              else
                echo "[init-job] ✓ Admin user already exists"
              fi

              # Verify authentication
              echo "[init-job] Verifying authentication..."
              if mongosh --host "${POD0_FQDN}" -u "${ROOT_USER}" -p "${ROOT_PWD}" --authenticationDatabase admin --eval "db.adminCommand('ping')" >/dev/null 2>&1; then
                echo "[init-job] ✅ Authentication successful!"
              else
                echo "[init-job] ⚠️  Note: Authentication will work once pods restart with keyFile enabled"
              fi

              echo ""
              echo "========================================="
              echo "[init-job] ✓ INITIALIZATION COMPLETE!"
              echo "========================================="
              echo ""
              echo "Replica Set: ${RS_NAME}"
              echo "Namespace: ${NAMESPACE}"
              echo "Username: ${ROOT_USER}"
              echo ""
              echo "Connection String:"
              echo "mongodb://${ROOT_USER}:${ROOT_PWD}@${RELEASE_FULLNAME}-service.${NAMESPACE}.svc.cluster.local:${MONGO_PORT}/admin?replicaSet=${RS_NAME}"
              echo ""
              echo "To enable full keyFile authentication, restart the pods:"
              echo "kubectl delete pod -n ${NAMESPACE} -l app.kubernetes.io/name=mongodb-ha"
              echo "========================================="

          env:
            - name: RELEASE_NAME
              value: "{{ .Release.Name }}"
